### ISSUE TITLE
Figure out utf-8 support

### ISSUE THREAD

**Issue by waterlink** [waterlink/crystal-mysql#13]
And look how it behaves for different encodings/collations

**Comment by drujensen** [comment]
:+1:  I ran into this issue. New to crystal but would love to help out.

**Comment by waterlink** [comment]
:+1: I haven't ran into that myself yet, but I have anticipated that there is something there to it. Can you post some insight or an example that demonstrates how it breaks when `utf-8` is used?

**Comment by drujensen** [comment]
Framework Benchmarks has a test called `fortunes` that has a table with one of the rows in UTF-8.  Here is the SQL to create the table. https://gist.github.com/drujensen/fd3cf9c3dffcafed5828

I am playing around with Amethyst and trying to complete all 6 tests.  Since there is no ORM, I created a rudimentary one on top of your driver. 

Here is the test project.  5 of the 6 tests are passing but it still needs tons of work. 
https://github.com/drujensen/FrameworkBenchmarks/tree/add_amethyst/frameworks/Crystal/amethyst

**Comment by waterlink** [comment]
There is actually an ORM: https://github.com/waterlink/active_record.cr along with respective adapter for this library: https://github.com/waterlink/mysql_adapter.cr

You can try to use them, but as you see you might bump up into problems, since everything is in pre-alpha quality. For instance this: #24

**Comment by drujensen** [comment]
@waterlink yes, i saw your work (excellent btw!) and I tried to integrate with Amethyst, but didn't see the mysql adapter.  I will re-attempt using it and let you know my progress.  Thanks!  Let me know if I can assist in supporting UTF-8.
